# Repository Service Checklist: __ENTITY_PASCAL__

- Workflow reference: `agents/workflows/repository-service.workflow.md`
- Generated by `scripts/create-repository-service.mjs` on __TIMESTAMP__

## Schema (Step 1)
- [ ] Complete `packages/core/schemas/schemas/__ENTITY_SLUG__/__ENTITY_CAMEL__.ts`
  - Flesh out domain attributes, refine `__ENTITY_PASCAL__IdSchema`, and update projections.
- [ ] Trim `packages/core/schemas/schemas/__ENTITY_SLUG__/__ENTITY_CAMEL__Create.ts` to include only caller inputs.
- [ ] Set accurate constants inside `packages/core/schemas/schemas/__ENTITY_SLUG__/constants/__ENTITY_CAMEL__.ts`.
- [ ] Replace the skipped tests in `packages/core/schemas/schemas/__ENTITY_SLUG__/__ENTITY_CAMEL__.schemas.test.ts` with focused coverage.
- [ ] Export any command/query schemas and re-export from the package index.

## Infrastructure (Step 2-3)
- [ ] Design DynamoDB keys/GSIs and update `cdk/backend-server-cdk/src/stacks/api-stack/__ENTITY_CAMEL__-table.constants.ts`.
- [ ] Implement resource creation inside `cdk/backend-server-cdk/src/stacks/api-stack/generate-__ENTITY_SLUG__-table.ts`.
- [ ] Wire `generate__ENTITY_PASCAL__Table` into `cdk/backend-server-cdk/src/stacks/api-stack/index.ts`.
- [ ] Update stack outputs (`cdk/backend-server-cdk/src/stacks/api-stack/index.ts` + Terraform output names) and extend `ApiStackOutputSchema`.
- [ ] Add the new output to `apps/node-server/src/clients/cdkOutputs.ts` and related stubs/tests.

## Service Layer (Step 4)
- [ ] Rename `tableName` placeholder inside `apps/node-server/src/services/__ENTITY_CAMEL__Repo.service.ts` to the real CDK output export.
- [ ] Map schema properties to DynamoDB operations (key attributes, GSIs, projections).
- [ ] Validate inputs with Effect-friendly errors aligned to domain rules.
- [ ] Register the Live layer in `apps/node-server/src/layers/app.layer.ts`.

## Fakes & Tests (Step 5-7)
- [ ] Tailor `apps/node-server/src/__tests__/fakes/__ENTITY_CAMEL__Repo.ts` to mirror the repository contract.
- [ ] Add repository unit tests under `apps/node-server/src/__tests__/services/` or package tests.
- [ ] Update handler/service slices to inject the new repository and cover integration behaviour.
- [ ] Wire CDK output stubs and fakes in existing suites as needed.

## Verification & Memory (Step 8)
- [ ] Run `npm run lint`, `npm run test`, and targeted CDK lint/synth commands.
- [ ] Update Memory Bank entries + add reflexion/progress log notes per workflow guidance.
- [ ] Execute `npm run memory:validate`, `npm run memory:drift`, and `npm run phase:check`.
